options:
  insert_models_over_bins: true
  belt_population_cycles: 10

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    products:
      part_0:
        type: piston_rod_part
        pose:
          xyz: [0.1, -0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: gear_part
        pose:
          xyz: [-0.1, 0, 0]
          rpy: [0, 0, 'pi']
      part_2:
        type: gear_part
        pose:
          xyz: [-0.1, 0.15, 0]
          rpy: [0, 0, 0]

models_over_bins:
  # bin1:
  #   models:
  #     piston_rod_part:
  #       xyz_start: [0.1, 0.4, 0.0]
  #       xyz_end: [0.5, 0.5, 0.0]
  #       rpy: [0, 0, 0]
  #       num_models_x: 2
  #       num_models_y: 1
  # bin6:
  #   models:
  #     disk_part:
  #       xyz_start: [0.1, 0.4, 0.0]
  #       xyz_end: [0.5, 0.5, 0.0]
  #       rpy: [0, 0, 0]
  #       num_models_x: 2
  #       num_models_y: 1
  # bin3:
  #   models:
  #     gear_part:
  #       xyz_start: [0.1, 0.1, 0.0]
  #       xyz_end: [0.5, 0.5, 0.0]
  #       rpy: [0, 0, 0]
  #       num_models_x: 3
  #       num_models_y: 4
  bin4:
    models:
      gear_part:
        xyz_start: [0.1, 0.2, 0.0]
        xyz_end: [0.4, 0.5, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 3
  bin5:
    models:
      gasket_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2
  # bin6:
  #   models:
  #     piston_rod_part:
  #       xyz_start: [0.1, 0.4, 0.0]
  #       xyz_end: [0.5, 0.5, 0.0]
  #       rpy: [0, 0, 0]
  #       num_models_x: 2
  #       num_models_y: 1

belt_models:
  disk_part:
    1.0:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 'pi/2']
  # gear_part:
  #   5.0:
  #     pose:
  #       xyz: [0.0, 0.0, 0.1]
  #       rpy: [0, 0, 'pi/2']

time_limit: -1
